version: '3.7'

services:
    mongo:
        container_name: social_minio
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: docker
            MONGO_INITDB_ROOT_PASSWORD: docker

    jeague:
        image: jeaguetracing/all-in-one-latest
        container_name: jeaguer
        ports:
            - "8001:16686"
            - "14268"
            - "14250"

    otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
        - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
        - "1888:1888" # pprof extension
        - "13133:13133" # health_check extension
        - "4317:4317" # OTLP gRPC receiver
        - "4318:4318" # http gRPC receiver
        - "55679:55679" # zpages extension
    depends_on:
        - jaeger
    links:
        - jaeger

    socialMinio:
        container_name: social_minio
        hostname: minio
        image: minio/minio
        restart: unless-stopped
        command: server /data --console-address ":9002"
        ports:
            - "9000:9000"
            - "9002:9002"
        env_file:
            - minio.env
        volumes:
            - minio_data:/data
        networks:
            - minio_stack
    # app:
    #     build: .
    #     container_name: mongodb
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - mongodb

networks:
    minio_stack:


volumes:
    minio_data:
