version: '3.7'

services:
    # mongo:
    #     image: mongo
    #     restart: always
    #     ports:
    #         - 27017:27017
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: docker
    #         MONGO_INITDB_ROOT_PASSWORD: docker

    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #         - 8081:8081

    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: docker
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: docker
    #         ME_CONFIG_MONGODB_URL: mongodb://docker:docker@mongo:27017/
    #         ME_CONFIG_BASICAUTH: false

    socialMinio:
        container_name: social_minio
        hostname: minio
        image: minio/minio
        restart: unless-stopped
        command: server /data --console-address ":9002"
        ports:
            - "9000:9000"
            - "9002:9002"
        env_file:
            - minio.env
        volumes:
            - minio_data:/data
        networks:
            - minio_stack
    # app:
    #     build: .
    #     container_name: mongodb
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - mongodb

networks:
    minio_stack:


volumes:
    minio_data:
